#!/usr/bin/env ruby

filename = ARGV[0]
raise "You need to pass in a filename to run!" if filename.nil?

folder = ARGV[0].split("/").first
file = ARGV[0].split("/").last

data_file = "data.txt"

if (ARGV[1] == "--test") 
    system("ruby #{folder}/#{file.sub(".rb", ".test.rb")}")
    exit
end

if !ARGV[1].nil? && ARGV[1] != "--profile"
    data_file = ARGV[1].sub("--", "") + ".txt"
end

executable = ""
if ARGV[1] == "--profile" || ARGV[2] == "--profile"
    # Hard coded! Eww!
    executable = "ruby /opt/homebrew/lib/ruby/gems/3.2.0/gems/ruby-prof-1.6.3/bin/ruby-prof"
end

data_filename = folder + "/" + data_file
if !File.exist?(data_filename)
    if data_file == "data.txt"
        day = folder.match(/day(\d*)/)[1].to_i

        require 'dotenv/load'
        API_TOKEN = ENV['API_TOKEN']
        response = `curl --cookie "session=#{API_TOKEN}" https://adventofcode.com/2024/day/#{day}/input`
        File.write(data_filename, response) 
    else
        print "No such file exists\n" 
        exit(1)    
    end
    
end

print "Data: #{data_filename}\n\n"

Dir.chdir(folder) do
    system("cat #{data_file} | #{executable} ./#{file}")
end


